package com.skyjetairlines.model.view;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 20 11:20:52 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FlightCapacityUtilizationVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DepartureAirport,
        ArrivalAirport,
        CapacityUtilization,
        AirportsVO1,
        AirportsVO2;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DEPARTUREAIRPORT = AttributesEnum.DepartureAirport.index();
    public static final int ARRIVALAIRPORT = AttributesEnum.ArrivalAirport.index();
    public static final int CAPACITYUTILIZATION = AttributesEnum.CapacityUtilization.index();
    public static final int AIRPORTSVO1 = AttributesEnum.AirportsVO1.index();
    public static final int AIRPORTSVO2 = AttributesEnum.AirportsVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FlightCapacityUtilizationVORowImpl() {
    }
}

