package com.skyjetairlines.model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 14:35:56 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FlightStatusVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FlightStatusVOImpl() {
    }
}

