package com.skyjetairlines.model.view;

import java.sql.Timestamp;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 19 17:28:52 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TotalRevenueFlightsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TotalRevenueFlightsVOImpl() {
    }
}

