package com.skyjetairlines.model.service.common;

import java.util.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 14 17:18:43 IST 2023
// ---------------------------------------------------------------------
public interface FlightManagementSystemAM extends ApplicationModule {
    void searchFlightsWithParams(String fromAirport, String toAirport, int numberOfSeats, Date bookingDate);
}

