package com.skyjetairlines.model.service;

import com.skyjetairlines.model.service.common.FlightManagementSystemAM;

import java.util.Date;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 14 17:11:47 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FlightManagementSystemAMImpl extends ApplicationModuleImpl implements FlightManagementSystemAM {
    /**
     * This is the default constructor (do not remove).
     */
    public FlightManagementSystemAMImpl() {
    }

    /**
     * Container's getter for BookingsInstance.
     * @return BookingsInstance
     */
    public ViewObjectImpl getBookingsInstance() {
        return (ViewObjectImpl) findViewObject("BookingsInstance");
    }

    /**
     * Container's getter for CustomersInstance.
     * @return CustomersInstance
     */
    public ViewObjectImpl getCustomersInstance() {
        return (ViewObjectImpl) findViewObject("CustomersInstance");
    }

    /**
     * Container's getter for FlightsInstance.
     * @return FlightsInstance
     */
    public ViewObjectImpl getFlightsInstance() {
        return (ViewObjectImpl) findViewObject("FlightsInstance");
    }

    /**
     * Container's getter for TicketsInstanceForBookings.
     * @return TicketsInstanceForBookings
     */
    public ViewObjectImpl getTicketsInstanceForBookings() {
        return (ViewObjectImpl) findViewObject("TicketsInstanceForBookings");
    }

    /**
     * Container's getter for AirportsArrivalInstanceForFlights.
     * @return AirportsArrivalInstanceForFlights
     */
    public ViewObjectImpl getAirportsArrivalInstanceForFlights() {
        return (ViewObjectImpl) findViewObject("AirportsArrivalInstanceForFlights");
    }

    /**
     * Container's getter for AirportsDepartureInstanceForFlights.
     * @return AirportsDepartureInstanceForFlights
     */
    public ViewObjectImpl getAirportsDepartureInstanceForFlights() {
        return (ViewObjectImpl) findViewObject("AirportsDepartureInstanceForFlights");
    }

    /**
     * Container's getter for TicketsInstanceForFlights.
     * @return TicketsInstanceForFlights
     */
    public ViewObjectImpl getTicketsInstanceForFlights() {
        return (ViewObjectImpl) findViewObject("TicketsInstanceForFlights");
    }

    /**
     * Container's getter for CurrentCustomerInstance.
     * @return CurrentCustomerInstance
     */
    public ViewObjectImpl getCurrentCustomerInstance() {
        return (ViewObjectImpl) findViewObject("CurrentCustomerInstance");
    }

    /**
     * Container's getter for BookingsInstanceForCurrentCustomer.
     * @return BookingsInstanceForCurrentCustomer
     */
    public ViewObjectImpl getBookingsInstanceForCurrentCustomer() {
        return (ViewObjectImpl) findViewObject("BookingsInstanceForCurrentCustomer");
    }

    /**
     * Container's getter for NotificationsInstanceForCurrentCustomer.
     * @return NotificationsInstanceForCurrentCustomer
     */
    public ViewObjectImpl getNotificationsInstanceForCurrentCustomer() {
        return (ViewObjectImpl) findViewObject("NotificationsInstanceForCurrentCustomer");
    }

    /**
     * Container's getter for PassengersInstanceForCurrentCustomer.
     * @return PassengersInstanceForCurrentCustomer
     */
    public ViewObjectImpl getPassengersInstanceForCurrentCustomer() {
        return (ViewObjectImpl) findViewObject("PassengersInstanceForCurrentCustomer");
    }

    /**
     * Container's getter for PaymentMethodsInstanceForCurrentCustomer.
     * @return PaymentMethodsInstanceForCurrentCustomer
     */
    public ViewObjectImpl getPaymentMethodsInstanceForCurrentCustomer() {
        return (ViewObjectImpl) findViewObject("PaymentMethodsInstanceForCurrentCustomer");
    }

    /**
     * Container's getter for TicketsInstanceForCurrentCustomer.
     * @return TicketsInstanceForCurrentCustomer
     */
    public ViewObjectImpl getTicketsInstanceForCurrentCustomer() {
        return (ViewObjectImpl) findViewObject("TicketsInstanceForCurrentCustomer");
    }

    /**
     * Container's getter for AirportsInstance.
     * @return AirportsInstance
     */
    public ViewObjectImpl getDepartureAirportsLOVInstance() {
        return (ViewObjectImpl) findViewObject("DepartureAirportsLOVInstance");
    }

    /**
     * Container's getter for BookingFkLink1.
     * @return BookingFkLink1
     */
    public ViewLinkImpl getBookingFkLink1() {
        return (ViewLinkImpl) findViewLink("BookingFkLink1");
    }

    /**
     * Container's getter for FlightArrivalAirportFkLink2.
     * @return FlightArrivalAirportFkLink2
     */
    public ViewLinkImpl getFlightArrivalAirportFkLink2() {
        return (ViewLinkImpl) findViewLink("FlightArrivalAirportFkLink2");
    }

    /**
     * Container's getter for FlightDepartureAirportFkLink2.
     * @return FlightDepartureAirportFkLink2
     */
    public ViewLinkImpl getFlightDepartureAirportFkLink2() {
        return (ViewLinkImpl) findViewLink("FlightDepartureAirportFkLink2");
    }

    /**
     * Container's getter for TicketsFlightsLink1.
     * @return TicketsFlightsLink1
     */
    public ViewLinkImpl getTicketsFlightsLink1() {
        return (ViewLinkImpl) findViewLink("TicketsFlightsLink1");
    }

    /**
     * Container's getter for BookingCustomerFkLink2.
     * @return BookingCustomerFkLink2
     */
    public ViewLinkImpl getBookingCustomerFkLink2() {
        return (ViewLinkImpl) findViewLink("BookingCustomerFkLink2");
    }

    /**
     * Container's getter for NotificationCustomerFkLink2.
     * @return NotificationCustomerFkLink2
     */
    public ViewLinkImpl getNotificationCustomerFkLink2() {
        return (ViewLinkImpl) findViewLink("NotificationCustomerFkLink2");
    }

    /**
     * Container's getter for PassengerCustomerFkLink3.
     * @return PassengerCustomerFkLink3
     */
    public ViewLinkImpl getPassengerCustomerFkLink3() {
        return (ViewLinkImpl) findViewLink("PassengerCustomerFkLink3");
    }

    /**
     * Container's getter for PayemntMethodCustomerFkLink2.
     * @return PayemntMethodCustomerFkLink2
     */
    public ViewLinkImpl getPayemntMethodCustomerFkLink2() {
        return (ViewLinkImpl) findViewLink("PayemntMethodCustomerFkLink2");
    }

    /**
     * Container's getter for BookingFkLink2.
     * @return BookingFkLink2
     */
    public ViewLinkImpl getBookingFkLink2() {
        return (ViewLinkImpl) findViewLink("BookingFkLink2");
    }

    public void searchFlightsWithParams(String fromAirport, String toAirport, int numberOfSeats, Date bookingDate,
                                        Integer bookedFlightId) {
        ViewObjectImpl flightsVO = this.getFlightsInstance();
        ViewCriteria searchFlightsVC = flightsVO.getViewCriteria("SerachFlightsViewCriteria");

        flightsVO.setNamedWhereClauseParam("b_fromAirport", fromAirport);
        flightsVO.setNamedWhereClauseParam("b_toAirport", toAirport);
        flightsVO.setNamedWhereClauseParam("b_numberOfSeats", numberOfSeats);
        flightsVO.setNamedWhereClauseParam("b_bookingDate", bookingDate);

        flightsVO.setNamedWhereClauseParam("b_bookedFlight", bookedFlightId);

        flightsVO.applyViewCriteria(searchFlightsVC);
        flightsVO.executeQuery();
    }

    /**
     * Container's getter for Airports1.
     * @return Airports1
     */
    public ViewObjectImpl getArrivalAirportsLOVInstance() {
        return (ViewObjectImpl) findViewObject("ArrivalAirportsLOVInstance");
    }

    /**
     * Container's getter for Airports2.
     * @return Airports2
     */
    public ViewObjectImpl getDepartureAirportsInstance() {
        return (ViewObjectImpl) findViewObject("DepartureAirportsInstance");
    }


    /**
     * Container's getter for Flights1.
     * @return Flights1
     */
    public ViewObjectImpl getFlightsInstanceForTicketsForCurrentCustomer() {
        return (ViewObjectImpl) findViewObject("FlightsInstanceForTicketsForCurrentCustomer");
    }

    /**
     * Container's getter for TicketsFlightsLink2.
     * @return TicketsFlightsLink2
     */
    public ViewLinkImpl getTicketsFlightsLink2() {
        return (ViewLinkImpl) findViewLink("TicketsFlightsLink2");
    }

    /**
     * Container's getter for TicketFlights1.
     * @return TicketFlights1
     */
    public ViewObjectImpl getTicketFlightsInstanceForTicketsForBookingForCurrentCustomer() {
        return (ViewObjectImpl) findViewObject("TicketFlightsInstanceForTicketsForBookingForCurrentCustomer");
    }

    /**
     * Container's getter for TicketFlightsticketFk1.
     * @return TicketFlightsticketFk1
     */
    public ViewLinkImpl getTicketFlightsticketFk1() {
        return (ViewLinkImpl) findViewLink("TicketFlightsticketFk1");
    }

    /**
     * Container's getter for CouponsPlace1.
     * @return CouponsPlace1
     */
    public ViewObjectImpl getCouponsPlaceInstance() {
        return (ViewObjectImpl) findViewObject("CouponsPlaceInstance");
    }

    /**
     * Container's getter for CouponsTime1.
     * @return CouponsTime1
     */
    public ViewObjectImpl getCouponsTimeInstance() {
        return (ViewObjectImpl) findViewObject("CouponsTimeInstance");
    }

    /**
     * Container's getter for CouponsRange1.
     * @return CouponsRange1
     */
    public ViewObjectImpl getCouponsRangeInstance() {
        return (ViewObjectImpl) findViewObject("CouponsRangeInstance");
    }

    /**
     * Container's getter for Coupons1.
     * @return Coupons1
     */
    public ViewObjectImpl getCouponsInstanceForFlights() {
        return (ViewObjectImpl) findViewObject("CouponsInstanceForFlights");
    }

    /**
     * Container's getter for FlightsCouponsLink1.
     * @return FlightsCouponsLink1
     */
    public ViewLinkImpl getFlightsCouponsLink1() {
        return (ViewLinkImpl) findViewLink("FlightsCouponsLink1");
    }
}

